# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
